openapi: 3.0.0
info:
  title: CRUD API
  description: API for CRUD operations on devices using AWS Lambda and S3 Designed by bhupendra.jmd@gmail.com
  version: 1.0.0
servers:
  - url: https://{api_id}.execute-api.{region}.amazonaws.com/prod
    variables:
      api_id:
        default: YOUR_API_ID
      region:
        default: YOUR_REGION
paths:
  /devices:
    get:
      summary: Get all devices
      description: Retrieve a list of all devices
      responses:
        '200':
          description: A JSON array of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    device_id:
                      type: integer
                      example: 1
                    device_type:
                      type: string
                      example: RPI
                    sensor_data:
                      type: object
                      properties:
                        temperature:
                          type: integer
                          example: 45
                        humidity:
                          type: integer
                          example: 85
    post:
      summary: Create a new device
      description: Create a new device with the specified details
      requestBody:
        description: Device object that needs to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                device_id:
                  type: integer
                  example: 1
                device_type:
                  type: string
                  example: RPI
                sensor_data:
                  type: object
                  properties:
                    temperature:
                      type: integer
                      example: 45
                    humidity:
                      type: integer
                      example: 85
      responses:
        '201':
          description: Device created successfully
          content:
            application/json:
              schema:
                type: string
                example: Device created
  /devices/{device_id}:
    get:
      summary: Get a device
      description: Retrieve a device by its ID
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: A device object
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_id:
                    type: integer
                    example: 1
                  device_type:
                    type: string
                    example: RPI
                  sensor_data:
                    type: object
                    properties:
                      temperature:
                        type: integer
                        example: 45
                      humidity:
                        type: integer
                        example: 85
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: string
                example: Device not found
    put:
      summary: Update a device
      description: Update the details of an existing device
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: Updated device object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                device_id:
                  type: integer
                  example: 1
                device_type:
                  type: string
                  example: RPI
                sensor_data:
                  type: object
                  properties:
                    temperature:
                      type: integer
                      example: 50
                    humidity:
                      type: integer
                      example: 80
      responses:
        '200':
          description: Device updated successfully
          content:
            application/json:
              schema:
                type: string
                example: Device updated
    delete:
      summary: Delete a device
      description: Delete a device by its ID
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Device deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: Device deleted
